dapperFramewoek/Controllers/HomeController.cs
using DapperEx;
using dapperFramewoek.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace dapperFramewoek.Controllers
{
    public class HomeController : Controller
    {
        public string connectionName = "DB";
        public DbBase CreateDbBase()
        {
            return new DbBase(connectionName);
        }
        public ActionResult Index(int pageIndex = 1, string name = "")
        {
            List<Account> list = new List<Account>();
            using (var db = CreateDbBase())
            {
                var sql = SqlQuery<Account>.Builder(db).AndWhere(m => m.Age, OperationMethod.Less, 20)
                     .LeftInclude()
                     .AndWhere(m => m.Name, OperationMethod.Contains, name)
                     .RightInclude();
                long pageCount = 0;
                //sql语句：
                //SELECT * FROM (SELECT ROW_NUMBER() OVER (ORDER BY Id) rid, * FROM Account WHERE Age < @Age1 AND ( Name LIKE @Name1 ) ) p_paged WHERE rid>0 AND rid<=0
                list = db.Page<Account>(pageIndex, 10, out pageCount, sql).ToList();
                ViewBag.PageList = ComHelper.PageList(pageCount, 10, pageIndex, "/Home?pageIndex={P}&name=" + name);
                return View(list);
            } 

        }

        public ActionResult List()
        {

            using (var db = CreateDbBase())
            {
                int pageCount = 0;
                string sql = @"select a.*,b.ProductName from OrderInfo as a inner join Product as b on a.ProductID=b.ID ";
                var list = db.getList<OrderInfo>(sql, out pageCount);
                return View(list);

                
            }
        }

        #region 新增
        public ActionResult Create(int id = 0)
        {
            Account model = new Account();
            model.CreateTime = DateTime.Now;
            return View(model);
        }
        [HttpPost]
        public ActionResult Create(Account model)
        {

            using (var db = CreateDbBase())
            {
                int  result = db.Insert<Account>(model);
                if (result>0)
                    return Content("添加成功");
                else
                    return Content("添加失败");
            }
        }
        #endregion


        #region 编辑
        public ActionResult Edit(int id = 0)
        {
            using (var db = CreateDbBase())
            {
                var sql = SqlQuery<Account>.Builder(db).AndWhere(m => m.Id, OperationMethod.Equal, id);
                var model = db.SingleOrDefault<Account>(sql);
                return View(model);
            }
        }
        [HttpPost]
        public ActionResult Edit(Account model)
        {
            using (var db = CreateDbBase())
            {
                var result = db.Update<Account>(model);
                if (result)
                    return Content("编辑成功");
                else
                    return Content("编辑失败");
            }
        }
        #endregion


        #region 获取Details
        public ActionResult Details(int id = 0)
        {
            using (var db = CreateDbBase())
            {
                var model = db.SingleOrDefault<Account>(SqlQuery<Account>.Builder(db)
                 .AndWhere(m => m.Id, OperationMethod.Equal, id));
                //取到用户的订单信息集合
                var sql = SqlQuery<OrderInfo>.Builder(db).AndWhere(m => m.AccountID, OperationMethod.Equal, id);
                model.listorderinfo = db.Query<OrderInfo>(sql).ToList();
                return View(model);
            }
        }



        public ActionResult Get(int id = 0)
        {
            using (var db = CreateDbBase())
            {
                var model = db.Get<Account>(id);
                return View(model);
            }
        }
        #endregion


        #region 删除Delete
        public ActionResult Delete(int id = 0)
        {
            using (var db = CreateDbBase())
            {

                var result = db.Delete<Account>(id);
            }
            return Content("删除成功");
        }
        #endregion


        #region 批量删除DeleteList
        /// <summary>
        /// 批量删除
        /// </summary>
        /// <param name="listId">需要删除的数据ID</param>
        /// <returns></returns>
        public ActionResult DeleteList(string listId = "")
        {
            using (var db = CreateDbBase())
            {
                var d = SqlQuery<Account>.Builder(db)
                 .AndWhere(m => m.Id, OperationMethod.In, listId);
                var result = db.Delete<Account>(d);
            }
            return View();
        }
        #endregion


    

    }
}

dapperFramewoek/Controllers/OrderInfoController.cs
using DapperEx;
using dapperFramewoek.Models;
using IYRSystemService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YRSystemService;


namespace dapperFramewoek.Controllers
{
    public class OrderInfoController : Controller
    {

        IOrderInfoService orderinfoservice = new OrderInfoService();

        public ActionResult Index(int pageIndex = 1,string key="")
        {
            long pageCount = 0;
            List<OrderInfo> list = orderinfoservice.getPage(pageIndex, 10, out pageCount, m => m.OrderDes, OperationMethod.Equal,key);
            ViewBag.PageList = ComHelper.PageList(pageCount, 10, pageIndex, "/OrderInfo?pageIndex={P}");
            return View(list);
        }


        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(OrderInfo orderinfo)
        {
            int id = orderinfoservice.Add(orderinfo);
            if (id > 0)
                return Content("添加成功");
            else
                return Content("添加失败");
        }


        public ActionResult Edit(int id)
        {
            OrderInfo orderinfo = orderinfoservice.GetModel(id);
            return View(orderinfo);
        }
        [HttpPost]
        public ActionResult Edit(OrderInfo orderinfo)
        {
           bool result=  orderinfoservice.Update(orderinfo);
           if (result)
               return Content("编辑成功");
           else
               return Content("编辑失败");
           
        }


        public ActionResult Details(int id=0)
        {
            OrderInfo orderinfo = orderinfoservice.GetModel(id);
            return View(orderinfo);
        }

        public ActionResult Delete(int id=0)
        {
           bool result= orderinfoservice.Delete(id);
           if (result)
               return Content("删除成功");
           else
               return Content("删除失败");
        }

    }
}

dapperFramewoek/Views/Home/Create.cshtml
@model dapperFramewoek.Models.Account

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Account</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreateTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreateTime)
            @Html.ValidationMessageFor(model => model.CreateTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Age)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Age)
            @Html.ValidationMessageFor(model => model.Age)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Flag)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Flag)
            @Html.ValidationMessageFor(model => model.Flag)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dapperFramewoek/Views/Home/Details.cshtml
@model dapperFramewoek.Models.Account

@{
    ViewBag.Title = "Details";
}

<h2>用户信息</h2>




<div class="display-label">
    @Html.DisplayNameFor(model => model.Name):
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Name)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Password):
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Password)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Email):
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Email)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.CreateTime):
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.CreateTime)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Age):
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Age)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Flag):
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Flag)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.AgeStr):
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.AgeStr)
</div>


<br />
<h1>----------订单信息-------------------</h1>
@if (Model.listorderinfo != null)
{
<table class="table table-striped table-bordered table-hover dataTables-example">
        <tr>
             <td>订单号</td>
             <td>订单备注</td>
        </tr>
        @foreach (var item in Model.listorderinfo)
        {
            <tr>
                <td>@Html.DisplayFor(itemmodel => item.OrderNum)</td>
                <td>@Html.DisplayFor(itemmodel => item.OrderDes)</td>
            </tr>         
        }
    </table>
}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dapperFramewoek/Views/Home/Edit.cshtml
@model dapperFramewoek.Models.Account

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Account</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreateTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreateTime)
            @Html.ValidationMessageFor(model => model.CreateTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Age)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Age)
            @Html.ValidationMessageFor(model => model.Age)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Flag)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Flag)
            @Html.ValidationMessageFor(model => model.Flag)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dapperFramewoek/Views/Home/Get.cshtml
@model dapperFramewoek.Models.Account

@{
    ViewBag.Title = "Get";
}

<h2>Get</h2>

<fieldset>
    <legend>Account</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Password)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Password)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CreateTime)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreateTime)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Age)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Age)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Flag)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Flag)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AgeStr)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AgeStr)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dapperFramewoek/Views/Home/Index.cshtml
@model IEnumerable<dapperFramewoek.Models.Account>

@{
    ViewBag.Title = "Index";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<p>

     @Html.ActionLink("订单列表", "Index","OrderInfo")
    @Html.ActionLink("新增", "Create")
    @Html.ActionLink("多表查询列表", "List")
</p>
@using (Ajax.BeginForm("Index", "Home", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "gray-bg", OnSuccess = "sbm" }, htmlAttributes: new { @class = "form-inline" }))
{
   
    <div class="form-group">
        &nbsp;姓名：<input type="text" id="key" class="form-control" name="name" style="margin-bottom: 5px;">

        <button class="btn btn-white" type="submit">查询</button>

        <a class="btn btn-outline btn-success" href="/Home/Index"><i class="glyphicon glyphicon-refresh"></i></a>
    </div>
}
<table class="table table-striped table-bordered table-hover dataTables-example">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Flag)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AgeStr)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Flag)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AgeStr)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })|
                 @Html.ActionLink("Get", "Get", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<div class="page">
    @Html.Raw(ViewBag.PageList)
</div>

dapperFramewoek/Views/Home/List.cshtml
@model IEnumerable<dapperFramewoek.Models.OrderInfo>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.productname)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.productname)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

dapperFramewoek/Views/OrderInfo/Create.cshtml
@model dapperFramewoek.Models.OrderInfo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>OrderInfo</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.OrderNum)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OrderNum)
            @Html.ValidationMessageFor(model => model.OrderNum)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OrderDes)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OrderDes)
            @Html.ValidationMessageFor(model => model.OrderDes)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AccountID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AccountID)
            @Html.ValidationMessageFor(model => model.AccountID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProductID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProductID)
            @Html.ValidationMessageFor(model => model.ProductID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dapperFramewoek/Views/OrderInfo/Details.cshtml
@model dapperFramewoek.Models.OrderInfo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>OrderInfo</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OrderNum)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OrderNum)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.OrderDes)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OrderDes)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AccountID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AccountID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.productname)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.productname)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dapperFramewoek/Views/OrderInfo/Edit.cshtml
@model dapperFramewoek.Models.OrderInfo

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>OrderInfo</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.OrderNum)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OrderNum)
            @Html.ValidationMessageFor(model => model.OrderNum)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OrderDes)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OrderDes)
            @Html.ValidationMessageFor(model => model.OrderDes)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AccountID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AccountID)
            @Html.ValidationMessageFor(model => model.AccountID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProductID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProductID)
            @Html.ValidationMessageFor(model => model.ProductID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

dapperFramewoek/Views/OrderInfo/Index.cshtml
@model IEnumerable<dapperFramewoek.Models.OrderInfo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Ajax.BeginForm("Index", "OrderInfo", new AjaxOptions { HttpMethod = "Post", UpdateTargetId = "gray-bg", OnSuccess = "sbm" }, htmlAttributes: new { @class = "form-inline" }))
{
   
    <div class="form-group">
        &nbsp;姓名：<input type="text" id="key" class="form-control" name="key" style="margin-bottom: 5px;">

        <button class="btn btn-white" type="submit">查询</button>

        <a class="btn btn-outline btn-success" href="/OrderInfo/Index"><i class="glyphicon glyphicon-refresh"></i></a>
    </div>
}
<table class="table table-striped table-bordered table-hover dataTables-example">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderDes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.productname)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderDes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AccountID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.productname)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
<div class="page">
    @Html.Raw(ViewBag.PageList)
</div>

dapperFramewoek/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>